### ISSUE TITLE
ODRC: Toevoegen andere organisaties en organisatieonderdelen

### ISSUE THREAD

**Issue by RutgerICATT** [GeneriekPublicatiePlatformWoo/ODRC#8]

**Comment by sergei-maertens** [comment]
Did some research into DiWoo for this - the relevant (root) specifications are `diwoo-metadata.xsd` and `diwoo-metadata-lijsten.xsd` (the latter is referenced by the former).

Long story  short the possible organisations (municipalities) are captured in waardenlijsten, which is translated into an enumeration in the XSD's. This means there's a fixed set of possible values _for stuff that needs to be published to the landelijke voorziening_ and we will have to populate these lists.

For example, a publication has a publisher/verantwoordelijke/mede-verantwoordelijken, which must be (one item of) an "organisatielijst", which is the union of "rwc_caribische_openbare_lichamen_compleet", "gemeentelijst", "ministerielijst"... and others

For now, given our context, I'd say we scope populating the Organisations from the "gemeentelijst", "solijst" and maybe "oorglijst"  too. For simplicity sake, we should expose this as a single model capturing the relevant (meta) data:

```yaml
Organisatie:
  type: object
  properties:
    identifier:  # acquired from waardelijst, or generated if it's a custom value
      type: string
      format: uri
    name:  # name/label of the organisation
      type: string
    origin:
      type: string
      enum:
        - gemeentelijst
        - solijst
        - oorglijst
        - zelf_toegevoegd  # can be edited, others cannot
    publicatieStatus:  # all records can be activated/deactivated
      type: string
      enum:
        - actief
        - niet_actief


OrganisatieOnderdeel:
  type: object
  properties:
    name:
      type: string
    organisatie:
      $ref: '#!/Organisatie.properties.identifier'
```
